#########################################
# Author : Philip Varghese Modayil
# Date   : 17.10.2024
# Topic  : Microstrip Arrangement Library
#########################################

######################################################################################
#                                      INFO
#######################################################################################
# This library includes functions that will calculate the various aspects of a single microstrip 
# arrangement approximation of a PCB. The functions follow the equations developed by Dr. Werner John.

#####################################################################################
#                                     Imports
#####################################################################################
import numpy as np
#from functools import lru_cache
from scipy.special import logsumexp
from typing import Tuple

import logging
# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

######################################################################################
#                            Necessary Conditions Check
######################################################################################
def isMonotonicallyDecreasing(g: np.ndarray) -> bool:
    """
    Function to check whether the suggested g values are monotonically decreasing
    Input
    -----------
    g: support points generated by the agent
        numpy array

    Output
    -----------
    boolean truth value 
    """
    # take the numpy differentiation
    dx = np.diff(g)
    
    # check if all first difference are negative
    # return the boolean value
    return np.all(dx < 0)

def degreeOfMonotonicity(g: np.ndarray) -> float:
    """
    Function to measure degree of monotonicity
    Input
    -----------
    g: support points generated by the agent
        numpy array

    Output
    -----------
    degree of monotonicity
    """   
    # take the numpy differentiation
    dx = np.diff(g)
    
    # count number of negative values
    return np.sum(dx<0)

# convex or concave function
def isConvex(g: np.ndarray) -> bool:
    """
    Function to check whether the suggested g values is a convex function
    Input
    -----------
    g: support points generated by the agent
        numpy array

    Output
    -----------
    boolean truth value 
    """
    # Check if the array has at least 3 elements
    if len(g) < 3:
        # print("The array should have at least 3 elements to perform convexity check.")
        return False
    
    # Calculate the second differences
    dx2 = g[2:] - 2 * g[1:-1] + g[:-2]
    
    # Check if all second differences are non-negative
    # return the boolean value
    return np.all(dx2 >= 0)

# degree of convexity
def degreeOfConvexity(g: np.ndarray) -> float:
    """
    Function to measure degree of convexity
    Input
    -----------
    g: support points generated by the agent
        numpy array

    Output
    -----------
    degree of convexity
    """
    
    # Calculate the second differences
    dx2 = g[2:] - 2 * g[1:-1] + g[:-2]
    
    # count number of positive values
    return np.sum(dx2>0)   

######################################################################################
#                              Potential & Potential Coeffs
######################################################################################
def filterVectors(hw_micrstr: float, hw_arra: float, g: np.ndarray, x: np.ndarray) -> Tuple[np.ndarray,np.ndarray]:
    """
    Takes out only the required values from the x and g vectors
    Parameters
    ----------
    hw_micrstr : float
        half width of the microstrip
    hw_arra : float
        half width of the arrangement
    g : np.ndarray
        support points y-axis from the agent
    x : np.ndarray
        support points x-axis

    Returns
    -------
    Tuple[np.ndarray]
        filtered x and g vectors
    """
    logger.info(f"Input x-axis and g-points vectors are being filtred. Input shapes: x={x.shape}, g={g.shape}")
    filterMask = (x > hw_micrstr) & (x < hw_arra)
    
    filteredX = x[filterMask]
    filteredG = g[filterMask]
    
    return filteredG, filteredX

def calculatePotentialCoeffs(V0: float, hw_micrstr: float, hw_arra: float, num_fs: int, g: np.ndarray, x: np.ndarray) -> np.ndarray:
    """
    Function to calaculate the potential coefficients parallelly
    This function taken in g values for corresponding x valueswhich are from (hw_micrstr + delta to hw_arra - delta)
    
    Input
    -----------
    V0: potential of the microstrip
        float
    hw_micrstr: halw width of the microstrip
        float
    hw_arra: half width of the arrangement
        float
    num_fs(N): number of fourier coefficients
        float
    g: support points y-axis from agent
        numpy array
    x: support points x-axis hw_micrstr < x < hw_arra
        numpy array
    
    Output
    -----------
    vn = potential coefficients  
        np.ndarray      
    """
    # dimensionality check
    if np.size(x) != np.size(g):
        raise Exception(f'Dimensions of x-axis vector and g-points vector do not match! \n size x:{np.size(x)}, size g:{np.size(g)}')
    
    # check for positional values, should contain values only for hw_micrstr < x-axis vector < hw_arra
    if x[0] == 0 or x[0] == hw_micrstr or x[-1] == hw_arra:
        # filter the vectors to keep between the required range
        g, x = filterVectors(hw_micrstr, hw_arra, g, x)
    
    n = np.arange(num_fs) # create a vector with fourier coefficients
    m = np.size(x) # size of the input vectors
  
    # check if input vector is sorted
    if not np.all(np.diff(x) > 0):
        logger.error("Input x-axis values are not sorted. Sorting......")
        x = np.sort(x)
        # Sort g accordingly
        g = g[np.argsort(x)]
    
    if m == 1: #Only one spline knot
        raise Exception('Not enough spline knots. Make sure there are at least 2 between half width of microstrip and half width of arrangement!')
    
    # for the formula to work exactly as written it requires at least 3 spline nots between hw_micrstr and hw_arra
    if m == 2: # with just 2 spline knots the formula is adjusted
        outer_coeff = 2/hw_arra*V0*(1/((2*n+1)*np.pi/(2*hw_arra))**2)

        v_n1 = (g[0]-V0)/(x[0]-hw_micrstr)*(np.cos((2*n+1)*x[0]*np.pi/(2*hw_arra))-np.cos((2*n+1)*hw_micrstr*np.pi/(2*hw_arra)))
        v_n3 = g[1]/(hw_arra-x[1])*np.cos((2*n+1)*x[1]*np.pi/(2*hw_arra))

        cos1 = np.cos(x[1]*np.pi/(2*hw_arra)*(2*n+1)) # 1xN
        cos2 = np.cos(x[0]*np.pi/(2*hw_arra)*(2*n+1)) # 1xN
        v_n2 = (g[1]-g[0])/(x[1]-x[0])*(cos1-cos2) # 1xN 
        v_n = outer_coeff*(v_n1+v_n2+v_n3)

        return v_n
    
    # for cases with more than 2 spline knots
    outer_coeff = 2/hw_arra*V0*(1/((2*n+1)*np.pi/(2*hw_arra))**2)
    v_n1 = (g[0]-V0)/(x[0]-hw_micrstr)*(np.cos((2*n+1)*x[0]*np.pi/(2*hw_arra))-np.cos((2*n+1)*hw_micrstr*np.pi/(2*hw_arra))) # 1xN
    v_n3 = g[-1]/(hw_arra-x[-1])*np.cos((2*n+1)*x[m-1]*np.pi/(2*hw_arra)) # 1xN

    x_t = np.reshape(x,(-1,1)) # convert 1 x m vector into a m x 1 vector (Transpose)

    cos1 = np.cos(x_t[1:m]*np.pi/(2*hw_arra)*(2*n+1)) # m-1x1 * 1xN = m-1xN
    cos2 = np.cos(x_t[0:m-1]*np.pi/(2*hw_arra)*(2*n+1))
    fac1 = (g[1:m]-g[0:m-1])/(x[1:m]-x[0:m-1]) # 1xm-1
    v_n2 = np.matmul(fac1,(cos1-cos2)) # 1xm-1 * m-1xN = 1xN

    v_n = outer_coeff*(v_n1+v_n2+v_n3) # 1xN

    return v_n

def calculatePotential(hw_arra: float, num_fs: int, vn:np.ndarray,x:np.ndarray) -> np.ndarray:
    """
    Function to calculate the potential

    Parameters
    ----------
    hw_arra : float
        half width of the arrangement
    num_fs : int
        number of fourier coefficients
    vn : np.ndarray
        potential coefficients
    x : np.ndarray
        support points x-axis

    Returns
    -------
    VF : np.ndarray
        potential
    """
    n = np.arange(num_fs)[:, np.newaxis] # create a vector with fourier coefficients Nx1
    
    cos1 = np.cos((2*n+1)*(np.pi/(2*hw_arra))*x) # Nxm
    VF = np.matmul(vn,cos1)
    
    return VF
    
######################################################################################
#                                        ENERGY
######################################################################################
# define logarithmic implementations for cosh and sinh to improve numerical stability
# sinh = (e^x - e^(-x))/2 => ln(sinh(x)) = ln(e^x - e^(-x)) - ln(2)
# cosh = (e^x + e^(-x))/2 => ln(cosh(x)) = ln(e^x + e^(-x)) - ln(2)
# logsumexp computes ln(e^x - e^(-x)) => max(x, -x) + ln(e^(x - max(x, -x)) + e^(-x - max(x, -x)))
# this ensures numerical stability as it reduces the values being calculated within exponential terms
######################################################################################
def logsinh(vector:np.ndarray) -> np.ndarray:
    """
    Auxiliary function
    Computes the natural logarithm of the sinh function, bypassing overflows that would happen if the sinh would be directly computed.
    """
    ones = np.ones_like(vector) # weight: equally weighted summation
    return logsumexp([vector, -vector], b=[ones, -ones], axis=0) - np.log(2) 

def logcosh(vector:np.ndarray) -> np.ndarray:
    """
    Auxiliary function
    Computes the natural logarithm of the cosh function, bypassing overflows that would happen if the cosh would be directly computed.
    """
    ones=np.ones_like(vector)
    return logsumexp([vector, -vector], b=[ones, ones], axis=0) - np.log(2) #If you encounter an overflow error here, you messed up big time. Please try another implementation or write your own.

def calculateEnergy(er1: float, er2: float, hw_arra: float, ht_arra: float, ht_subs: float, num_fs: int, vn: np.ndarray) -> float:
    """
    Function to calaculate the total energy of the arrangement
    
    Input
    -----------
    er1: permitivitty of medium 1
        float
    er2: permitivitty of medium 2
        float
    hw_arra: half width of the arrangement
        float
    ht_arra: height of the arrangement
        float
    ht_subs: height of the substrate
        float
    num_fs: number of fourier coefficients
        int
    vn: array of potential coefficients
        numpy array
    
    Output
    -----------
    W12 = total energy of the arrangement  
        float     
    """
    e1 = er1*8.854E-12 # 8.54E-12 is permittivity constant e0
    e2 = er2*8.854E-12 
    
    # following the formula
    ###########################################################################################
    n = np.arange(num_fs) # create a vector with fourier coefficients
    
    coeff = (2*n+1)*np.pi*vn**2 # 1 x N
    # w1
    ###########################################################################################
    logcosh1 = logcosh((2*n+1)*np.pi*(ht_arra-ht_subs)/(2*hw_arra)) # 1 x N
    logsinh1 = logsinh((2*n+1)*np.pi*(ht_arra-ht_subs)/(2*hw_arra)) # 1 x N

    coth1 = np.exp(logcosh1-logsinh1) # log(cosh/sinh) = log(cosh) - log(sinh)
    w1 = e1/4*np.sum(coeff*coth1)

    # w2
    ###########################################################################################
    logcosh2 = logcosh((2*n+1)*np.pi*ht_subs/(2*hw_arra)) # 1 x N
    logsinh2 = logsinh((2*n+1)*np.pi*ht_subs/(2*hw_arra)) # 1 x N

    coth2 = np.exp(logcosh2-logsinh2)
    w2 = e2/4*np.sum(coeff*coth2)

    W12 = w1+w2
    
    
    return W12

######################################################################################
#                        Capacitance, Impedance, Epsilon Effective
######################################################################################
def calculateCapacitance(V0: float, W:float) -> float:
    """
    Function to calaculate capacitance
    
    Input
    -----------
    W: energy
        float
    
    Output
    -----------
    C = capacitance  
        float      
    """
    
    C = (2*W)/(V0**2)
    
    return C

def calculateImpedanceCaseD(cD: float, cL: float) -> float:
    """
    calculates capacitance of case D
    Parameters
    ----------
    capacitanceD : float
        case D capacitance
    capacitanceL : float
        case L capacitance

    Returns
    -------
    zD: float
        impedance case D
    """
    c0 = 299792458 #m/s speed of light in vaccuum
    return 1/(c0*(cD*cL)**0.5)

def calculateImpedanceCaseL(cL: float) -> float:
    """
    calculates capacitance of case L
    Parameters
    ----------
    capacitanceL : float
        case L capacitance

    Returns
    -------
    zL: float
        impedance case L 
    """
    c0 = 299792458 #m/s speed of light in vaccuum
    return 1/(c0*cL)

def calculateEpsilonEffective(cD: float, cL: float) -> float:
    """
    calculates effective dielectric constant

    Parameters
    ----------
    cD : float
        case D capacitance
    cL : float
        case L capacitance

    Returns
    -------
    eps_eff: float
        effective dielectric constant
    """
    return cD/cL

######################################################################################
#                           Surface Charge Density
######################################################################################

def calculateChargeDensityCoeffs(er1: float, er2: float, hw_arra: float, ht_arra: float, ht_subs: float, num_fs: int, vn: np.ndarray) -> np.ndarray:
    """
    calculates the charge density coefficients sigma_n
    
    Input
    -----------
    er1: permitivitty of medium 1
        float
    er2: permitivitty of medium 2
        float
    hw_arra: half width of the arrangement
        float
    ht_arra: height of the arrangement
        float
    ht_subs: height of the substrate
        float
    num_fs: number of fourier coefficients
        int
    vn: array of potential coefficients
        numpy array
    
    Output
    -----------
    sigma_n = charge density coefficients
        float     
    """
    e1 = er1*8.854E-12 # 8.54E-12 is permittivity constant e0
    e2 = er2*8.854E-12 
    
    # following the formula
    ###########################################################################################
    n = np.arange(num_fs) # create a vector with fourier coefficients
    
    outer_coeff = vn*(2*n+1)*np.pi/(2*hw_arra)
    
    logcosh2 = logcosh((2*n+1)*np.pi*(ht_subs)/(2*hw_arra)) # 1 x N
    logsinh2 = logsinh((2*n+1)*np.pi*(ht_subs)/(2*hw_arra)) # 1 x N
    coth2 = np.exp(logcosh2 - logsinh2)
    
    logcosh1 = logcosh((2*n+1)*np.pi*(ht_arra-ht_subs)/(2*hw_arra)) # 1 x N
    logsinh1 = logsinh((2*n+1)*np.pi*(ht_arra-ht_subs)/(2*hw_arra)) # 1 x N
    coth1 = np.exp(logcosh1 - logsinh1)
    
    sigma_n = outer_coeff*(e2*coth2 + e1*coth1)
    
    return sigma_n

def calculateChargeDensity(er1: float, er2: float, ht_arra: float, ht_subs: float, hw_arra: float, num_fs: int, vn:np.ndarray,x:np.ndarray) -> np.ndarray:
    """
    ccalculates surface charge density

    Parameters
    ----------
    er1: permitivitty of medium 1
        float
    er2: permitivitty of medium 2
        float
    ht_arra: height of the arrangement
        float
    ht_subs: height of the substrate
        float
    hw_arra : float
        half width of the arrangement
    num_fs : int
        number of fourier coefficients
    vn : np.ndarray
        potential coefficients
    x : np.ndarray
        support points x-axis

    Returns
    -------
    Sigma : np.ndarray
        surface charge density
    """
    sigma_n = calculateChargeDensityCoeffs(er1, er2, hw_arra, ht_arra, ht_subs, num_fs, vn)
    n = np.arange(num_fs)[:, np.newaxis] # create a vector with fourier coefficients Nx1
    
    cos1 = np.cos((2*n+1)*(np.pi/(2*hw_arra))*x) # Nxm
    Sigma = np.matmul(sigma_n,cos1)
    
    return Sigma