#######################################
# Author : Philip Varghese Modayil
# Date   : 22.05.2023
# Topic  : Microstrip Arrangement 
#######################################

# importing libraries
import numpy as np
import mpmath as mp

# class to hold the microstrip arrangement functions
class MicroStripArrangement:
    """
    This class initializes a micro strip arrangement and encapsulates the functions to calculate its properties
    """
    # constructor function 
    def __init__(self,V0,hw_arra,ht_arra,ht_subs,hw_micrstr,ht_micrstr,er_1,er_2,num_fs) -> None:
        self.V0 = V0 # potential of the microstrip
        self.hw_arra = hw_arra # half width of the arrangement
        self.ht_arra = ht_arra # height of the arrangement
        self.ht_subs = ht_subs # height of the substrate
        self.hw_micrstr = hw_micrstr # half width of the microstrip
        self.ht_micrstr = ht_micrstr # height of the microstrip
        self.er_1 = er_1 # relative permitivitty of medium 1(usually air)
        self.er_2 = er_2 # relative permitivitty of medium 2
        self.e0 = 8.85418781762e-12 # dielectric constant
        self.c = 299792458 # speed of light in vacuum (m/s)
        self.w_arra = 2*self.hw_arra # width of the arrangement
        self.w_micrstr = 2*self.hw_micrstr # width of the microstrip
        self.e1 = self.e0*self.er_1 # permitivitty of medium 1
        self.e2 = self.e0*self.er_2 # permitivitty of medium 2
        self.num_fs = num_fs # number of fourier coefficients(vn)
    
    # function to check monotonicity
    def monotonically_decreasing(self,g) -> bool:
        """
        Function to check whether the suggested g values are monotonically decreasing
        Input
        -----------
        g: support points generated by the agent
            numpy array
    
        Output
        -----------
        boolean truth value 
        """
        # take the numpy differentiation
        dx = np.diff(g)
        
        # check if all first difference are negative
        # return the boolean value
        return np.all(dx < 0)    
    
    # convex or concave function
    def is_convex(self,g) -> bool:
        """
        Function to check whether the suggested g values is a convex function
        Input
        -----------
        g: support points generated by the agent
            numpy array
    
        Output
        -----------
        boolean truth value 
        """
        # Check if the array has at least 3 elements
        if len(g) < 3:
            # print("The array should have at least 3 elements to perform convexity check.")
            return False
        
        # Calculate the second differences
        dx2 = g[2:] - 2 * g[1:-1] + g[:-2]
        
        # Check if all second differences are non-negative
        # return the boolean value
        return np.all(dx2 >= 0)

    def potential_coeff(self,g,x):
        """
        Function to calaculate the potential coefficients
        This function taken in g values for corresponding x valueswhich are from (hw_micrstr + delta to hw_arra - delta)
        
        Input
        -----------
        V0: potential of thhe microstrip
            double
        g: support points y-axis from agent
            numpy array
        x: support points x-axis
            numpy array
        hw_micrstr: halw width of the microstrip
                double
        hw_arra: half width of the arrangement
                double
        num_fs: number of fourier coefficients
                double
        
        Output
        -----------
        vn = potential coefficients  
            double      
        """
        vn = []
        # repeat for num_fs times
        for n in range(self.num_fs):
            
            vn_n = ((g[0] - 1)/(x[0] - self.hw_micrstr))*(mp.cos((2*n+1)*mp.pi/(2*self.hw_arra)*x[0]) - mp.cos((2*n+1)*mp.pi/(2*self.hw_arra)*self.hw_micrstr))
            
            for i in range(1,len(x)):
                vn_n += ((g[i] - g[i-1])/(x[i] - x[i-1]))*(mp.cos((2*n+1)*mp.pi/(2*self.hw_arra)*x[i]) - mp.cos((2*n+1)*mp.pi/(2*self.hw_arra)*x[i-1]))
            
            vn_n += (g[-1]/(self.hw_arra - x[-1]))*mp.cos((2*n+1)*mp.pi/(2*self.hw_arra)*x[-1])
            vn_n *= 2/self.hw_arra*(self.V0/((2*n+1)*mp.pi/(2*self.hw_arra))**2)
            
            vn.append(vn_n)
        return vn

    # function to calculate the energy of the arrangement
    def energy(self,v):
        """
        Function to calaculate the total energy of the arrangement
        
        Input
        -----------
        e1: permitivitty of medium 1
            double
        e2: permitivitty of medium 2
            double
        v: array of potential coefficients
            numpy array
        hw_arra: halw width of the arrangement
                double
        ht_arra: height of the arrangement
                double
        ht_subs: height of the substrate
                double
        
        Output
        -----------
        w12 = total energy of the arrangement  
            double      
        """
        # follow the formula
        w1 = 0
        w2 = 0
        for n in range(len(v)):
            w1 += (v[n]**2)*(2*n+1)*mp.pi*mp.coth((2*n+1)*mp.pi*(self.ht_arra - self.ht_subs)/(2*self.hw_arra))
            w2 += (v[n]**2)*(2*n+1)*mp.pi*mp.coth((2*n+1)*mp.pi*(self.ht_subs)/(2*self.hw_arra))
         
        w12 = self.e1*w1/4 + self.e2*w2/4
        
        return w12